# Generated by Django 3.1.2 on 2020-10-10 01:08

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('bio', models.CharField(max_length=300)),
            ],
            managers=[
                ('directors', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('action', 'Action'), ('adventure', 'Adventure'), ('animation', 'Animation'), ('comedy', 'Comedy'), ('crime', 'Crime'), ('drama', 'Drama'), ('history', 'History'), ('romance', 'Romance'), ('sci-fi', 'Sci-fi'), ('war', 'War')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('release_date', models.DateField()),
                ('plot', models.TextField(max_length=500)),
                ('runtime', models.IntegerField()),
                ('poster_image', models.ImageField(blank=True, null=True, upload_to='movie-poster/')),
                ('poster_image_url', models.URLField(blank=True, null=True)),
                ('language', models.CharField(choices=[('english', 'English'), ('french', 'French'), ('german', 'German'), ('spanish', 'Spanish'), ('hindi', 'Hindi'), ('tamil', 'Tamil')], max_length=50)),
                ('director', models.ManyToManyField(blank=True, related_name='directed_movies', to='movies.Artist')),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movies', to='movies.genre')),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_played', to='movies.artist')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='movies.movie')),
            ],
        ),
    ]
